AM/urls.py
from django.conf.urls import patterns, include, url
from AM import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^', include('app_camas.urls')),
    url(r'^', include('app_solicitudes.urls')),
    url(r'^', include('app_usuario.urls')),
    url(r'^', include('app_estadisticas.urls')),
	url(r'^', include('app_paciente.urls')),
	
	(r'^selectable/', include('selectable.urls')),


    ## COSAS DJANGISTICAS
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    # Media
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    # Static
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.STATIC_ROOT}),


    # Examples:
    # url(r'^$', 'AM.views.home', name='home'),
    # url(r'^AM/', include('AM.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

app_paciente/forms.py
from django import forms
from models import *

class agregar_paciente_form(forms.Form):
    num_historia     = forms.IntegerField(
                            max_value=999999,
                            widget = forms.TextInput(attrs={'size': 6}))
    tipo_cedula      = forms.ChoiceField(
                            choices=TIPO_CEDULA,
                            widget=forms.RadioSelect())
    cedula           = forms.IntegerField(max_value=999999999)
    nombres          = forms.CharField(max_length=64)
    apellidos        = forms.CharField(max_length=64)
    sexo             = forms.ChoiceField(choices=SEXO)
    
    fecha_nacimiento          = forms.DateField(
                        label = "FECHA DE NACIMIENTO",
                        widget = forms.TextInput(attrs = {
                            'placeholder':'dd/mm/aaaa',
                            'data-format':'dd/mm/yyyy'
                            }))
    fecha_ingreso_institucion = forms.DateField(
                        label = "FECHA DE INGRESO A LA INSTITUCION",
                        widget = forms.TextInput(attrs = {
                            'placeholder':'dd/mm/aaaa',
                            'data-format':'dd/mm/yyyy'
                            }))

app_usuario/forms.py
from django import forms
from models import *
from django.forms.widgets import CheckboxSelectMultiple


class IniciarSesionForm(forms.Form):
    unombre = forms.CharField(
                      max_length = 64,
                      widget = forms.TextInput(
                                 attrs = {
                                     'placeholder': 'Cedula de identidad:',
                                     'class': 'span2'
                                     }))
    uclave = forms.CharField(max_length = 32,
                             widget = forms.PasswordInput(attrs = {
                                 'placeholder':'Clave:',
                                 'class':'span2'
                                 }))


class SolicitarCuenta(forms.Form):
    cedula          = forms.IntegerField(widget=forms.TextInput)
    nombres         = forms.CharField()
    apellidos       = forms.CharField()
    tipo            = forms.ChoiceField(choices = USUARIO)
    email           = forms.EmailField(max_length = 64)
    email0          = forms.EmailField(max_length = 64)
    clave           = forms.CharField(widget = forms.PasswordInput())
    clave0          = forms.CharField(widget = forms.PasswordInput())
    administrador   = forms.BooleanField(required = False)

#class cambioClave(forms.Form):
    #claveV = forms.CharField(widget = forms.PasswordInput())
    #clave = forms.CharField(widget = forms.PasswordInput())
    #claveO = forms.CharField(widget = forms.PasswordInput())

#class restablecerClave(forms.Form):
    #correo = forms.EmailField(max_length = 64)

templates/agregarPaciente.html
{% extends "base.html" %} 
{% block scripts %}
  <!--Datetime Picker -->
  <script type="text/javascript"
    src="/static/libs/datepicker/js/bootstrap-datetimepicker.min.js"></script>
  <link rel="stylesheet"
    href="/static/libs/datepicker/css/bootstrap-datetimepicker.min.css">
{% endblock %} 

{% block cuerpo %}
  <div class="row">
    <div class="cuadroGrande span12 centrar">
      <h4>Agregar Paciente</h4>
      <form id="formulario" 
            class="tablaAgregar" 
            method="post"
            action="/emergencia/agregar">
        {% csrf_token %}
        <table>
          {% for e in form %}
            <tr>
              {% if e.label == "FECHA Y HORA DE INGRESO" %}
                <td>
                {{e.label}}
                </td>
                <td>
                  <div id="ingreso_picker" 
                       class="input-append">
                    {{e}}
                    <span id="ahora" 
                          class="btn">Ahora
                    </span> 
                    <span  class="add-on">
                      <i data-time-icon="icon-time"
                         data-date-icon="icon-calendar"> 
                       </i>
                    </span>
                  </div>
                    <script type="text/javascript">
                      $(function() {
                        $('#ingreso_picker').datetimepicker({
                          language: 'pt-BR'
                        });
						
						// Se cierra el calendario al seleccionar fecha
						$('#ingreso_picker').on('changeDate', function(e) {
						  $('#ingreso_picker').datetimepicker('hide');
						});
                      });
                    </script>
                </td>
                <td>
                  {{e.errors}}
                </td> 
              {% elif e.label == "DOCUMENTO DE IDENTIDAD" %}
                <td>{{e.label}}</td>
                <td>
                  <select id="id_cedula1" 
                          name="dia" 
                          class = "width60"
                          onchange="cambioFecha()">
                    <option value='V'>
                      V
                    </option>
                    <option value='E'>
                      E
                    </option>
                    <option value='P'>
                      P
                    </option>
                  </select>
                  &nbsp;&nbsp;
                  <input id="id_cedula2" 
                         maxlength="9" 
                         name="cedula"
                         type="text" 
                         class = "width170"
                         onblur="documentoId()"
                         onkeypress="return justNumbers(event);" 
                   /> 
                   <input id="id_cedula"
                          maxlength="9" 
                          name="cedula" 
                          type="hidden" 
                   />
                </td>
                <td>
                  {{e.errors}}
                </td>
              {% elif e.label == "NOMBRE" %}
                <td>
                  {{e.label}}
                </td>
                <td>
                  <input id="id_nombres" 
                         maxlength="64" 
                         name="nombres"
                         type="text" 
                         onkeyup="this.value=this.value.toUpperCase()" 
                  />
                </td>
                <td>
                  {{e.errors}}
                </td> 
              {% elif e.label == "APELLIDO" %}
                <td>
                  {{e.label}}
                </td>
                <td>
                  <input id="id_apellidos" 
                         maxlength="64" 
                         name="apellidos"
                         type="text" 
                         onkeyup="this.value=this.value.toUpperCase()" 
                  />
                </td>
                <td>
                  {{e.errors}}
                </td> 
              {% elif e.label == "FECHA DE NACIMIENTO" %}
                <td></td>
                <td>
                  <span class="label label-info">
                    DIA
                  </span>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  <span class="label label-info">
                    MES
                  </span>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  <span class="label label-info">
                    AÑO
                  </span>
                  &nbsp;&nbsp;
                </td>
                <td></td>
            </tr>
              <tr>
                <td>
                  {{e.label}}
                </td>
                <td>
                  <select id="dia" 
                          name="dia" 
                          class = "width60"
                          onchange="cambioFecha()">
                  </select>
                  &nbsp;&nbsp; 
                  <select id="mes" 
                          name="mes" 
                          class = "width60"
                          onchange="cambioFecha()">
                  </select> 
                  &nbsp;&nbsp; 
                  <select id="ano" 
                          name="ano" 
                          class = "width80"
                          onchange="cambioFecha()">
                  </select> 
                  <input id="id_fecha_nacimiento" 
                         name="fecha_nacimiento"
                         type="hidden">
                </td>
                <td>
                  {{e.errors}}
                </td> 
              {% else %}
                <td>
                  {{e.label}}
                </td>
                <td>
                  {{e}}
                </td>
                <td>
                  {{e.errors}}
                </td> 
              {% endif %}
              </tr>
          {% endfor %}
          <tr>
            <td></td>
            <td>
              <input class="btn btn-primary" 
                     type="submit"
                     value="Ingresar" 
              />
            </td>
            <td></td>
          </tr>
        </table>
      </form>
    </div>
  </div>
{% endblock %}
 
{% block scripts2 %}
<script>
  function documentoId(){
    var tipo = $("#id_cedula1").val();
    var documento = $("#id_cedula2").val();
    if (documento != ""){
      $("#id_cedula").attr("value",tipo+"-"+documento);
    }else{
      $("#id_cedula").attr("value","");
    }
  }

  function justNumbers(e){
    var keynum = window.event ? window.event.keyCode : e.which;
    if ((keynum == 8) || (keynum == 46)) return true;   
    return /\d/.test(String.fromCharCode(keynum));
  }

  function cambioFecha(){
    var dia = $("#dia").val();
    var mes = $("#mes").val();
    var ano = $("#ano").val();
    $("#id_fecha_nacimiento").attr("value",dia+"/"+mes+"/"+ano);
  }

  $(document).ready(function() {  
	  $("#ahora").click(function() {
	    var currentTime = new Date();
	    var mes = currentTime.getMonth() + 1;
	    var dia = currentTime.getDate();
	    var año = currentTime.getFullYear();
	
	    var horas    = currentTime.getHours()
	    var minutos  = currentTime.getMinutes()
	    var segundos = currentTime.getSeconds()
	    $("#id_ingreso").val(dia + "/" + mes +"/" + año + " " + horas + ":" + 
	                         minutos+":"+segundos)});
  });   
   
  var dia  = 1,mes = 1,ano = 1990;
  $("#dia").html("<option value='nada'>--</option>");
  $("#dia > option[value='nada']").after("<option value='"+ 1 +"'>"+ 1 
                                        +"</option>");
  for (dia =2;dia<=31;dia++){
    $("#dia > option[value='" + (dia-1) +"']").after("<option value='" + dia 
     + "'>"+dia+"</option>");      
  }
  $("#mes").html("<option value='nada'>--</option>");
  $("#mes > option[value='nada']").after("<option value='"+1+"'>"+1+"</option>");
  for (mes =2;mes<=12;mes++){
    $("#mes > option[value='"+(mes-1)+"']").after("<option value='"+mes+"'>"+
                                                 mes+"</option>");      
  }
  var currentTime = new Date();
  $("#ano").html("<option value='nada'>--</option>");
  //alert(currentTime.getFullYear());
  $("#ano > option[value='nada']").after("<option value='" +
                                         currentTime.getFullYear() + "'>" +
                                         currentTime.getFullYear()+"</option>");
  for (ano =currentTime.getFullYear();ano>=1900;ano--){
    $("#ano > option[value='"+(ano+1)+"']").after("<option value='" + ano +
                                                  "'>"+ano+"</option>");
  }

</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
  
  <title>Atenci&oacute;n M&eacute;dica</title>
  
  <!-- jQuery -->
  <link rel="stylesheet" 
        href="{{ STATIC_URL }}libs/jquery/themes/smoothness/jquery-ui.css">
  <!-- Bootstrap -->
  <link rel="stylesheet" 
        href="{{ STATIC_URL }}libs/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" 
        href="{{ STATIC_URL }}libs/bootstrap/css/bootstrap-responsive.min.css">
  <!-- Propios -->
  <link rel="stylesheet" href="{{ STATIC_URL }}css/estilo.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/masEstilos.css">
  {% block styles %}
  {% endblock %}
  
  
  <link type="image/x-icon" href="{{ STATIC_URL }}img/icono.ico" rel="icon" />
  
  
  <!-- jQuery -->
  <script src="{{ STATIC_URL }}libs/jquery/js/jquery.min.js"></script>
  <script src="{{ STATIC_URL }}libs/jquery/js/jquery.js"></script>
  <script src="{{ STATIC_URL }}libs/jquery/js/jquery-ui.js"></script>
  <!-- Bootstrap -->
  <script src="{{ STATIC_URL }}libs/bootstrap/js/bootstrap.min.js"></script>
  <script src="{{ STATIC_URL }}libs/bootstrap/js/bootstrap-dropdown.js"></script>
  <script src="{{ STATIC_URL }}libs/bootstrap/js/bootstrap-collapse.js"></script>
  
  <script>
      // Para habilitar el dropdown de los menus
      $(document).ready(function(){
        $('.dropdown-toggle').dropdown();
      });
  </script>
  {% block scripts %}
  {% endblock %}
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>


<body>
  <div id="lista" class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-inner fontsize16">
      <div class="container">
      
        <a  class="btn btn-navbar" 
            data-toggle="collapse"
            data-target=".nav-collapse"> 
          <span class="icon-bar"></span>
          <span class="icon-bar"></span> 
          <span class="icon-bar"></span>
        </a>
        
        <a class="brand" href="/">
          <img src="/static/img/logo.png"
               class="marginleft5 width40 height40" />
        </a>
        
        <div class="nav-collapse"> 
          <ul class="nav">          
            {% if user.is_authenticated %}
                {% if user.is_staff %}
                
                <li class="dropdown">
                    <a href="/censo">
                        Censo
                    </a>
                </li>
                
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Habitaciones
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="/habitacion/asignar">Asignar</a>
                        </li>
                        <li>
                            <a href="/habitacion/solicitar">Solicitar</a>
                        </li>
                    </ul>
                </li>
                
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Term&oacute;metro
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="/estadisticas/termometro">Term&oacute;metro</a>
                        </li>
                        <li>
                            <a href="/estadisticas/matriz">Matriz</a>
                        </li>
                    </ul>
                </li>
                
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Usuarios
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="/usuario/crear">Agregar</a>
                        </li>
                        <li>
                            <a href="/usuario/buscar">Buscar</a>
                        </li>
                        <li>
                            <a href="/usuario/listar">Listar</a>
                        </li>
                    </ul>
                </li>
              
                {% else %}
                <li>
                  <a href="/emergencia/buscar">Paciente</a>
                </li>
                <li>
                  <a href="/emergencia/listar/todas">Ver emergencias</a>
                </li>
                <li class="dropdown">
                    <a  href="#" class="dropdown-toggle"
                        data-toggle="dropdown">
                      Listas por categoría
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li>
                    <a href="/emergencia/listar/todas">
                        Pacientes en emergencia
                    </a>
                    </li>
                    <li class="divider">
                    </li>
                    <li class="nav-header">Por área
                    </li>
                    <li>
                        <a href="/emergencia/listar/triage">
                        Pacientes en triage
                        </a>
                    </li>
                    <li>
                        <a href="/emergencia/listar/atencion">
                        Pacientes en atención
                        </a>
                    </li>
                    <li class="divider">
                    </li>
                    <li class="nav-header">
                        Subáreas de triage
                    </li>
                    <li>
                        <a href="/emergencia/listar/sinclasificar"> 
                        Pacientes sin clasificar
                        </a>
                    </li>
                    <li>
                    <a href="/emergencia/listar/clasificados">
                        Pacientes clasificados, no atendidos
                    </a>
                    </li>
                    </ul>
                </li> 
                {% endif %}
            {% endif %}
          </ul>
        </div>
        
        
        {% if user.is_authenticated %}
        <div class="usuario navbar-form pull-right">
            {{user}} 
            (<a href="/sesion/cerrar">Cerrar sesión</a>)
        </div>
        {% else %}
        <form method='POST' 
              action="/sesion/iniciar/"
              class="navbar-form pull-right">
          {% csrf_token %}
          {{ form.unombre }} 
          {{ form.uclave }} 
          <input  class="btn btn-primary" 
                  type="submit"
                  value="Iniciar Sesi&oacute;n" />
          <br> 
          <a href="/usuario/restablecer">Recuperar clave</a> 
          |
          <a href="/usuario/solicitar">Solicitar cuenta</a>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
  
  
  <div id="cuerpo" class="container">
    {% if msj_info %}
      <div class="row">
        <div id="mensaje" class="span12 alert alert-{{msj_tipo}}">
          {{msj_info}}
        </div>
      </div>
    {% endif %} 
    
    {% if not user.is_authenticated %}
      <h3 class="tit-list"></h3>
    {% endif %} 
	
	{% if messages %}
	<div onclick="$(this).fadeOut()" style="position: absolute; left: 50%; top:20px;z-index:2000;">
		<div style="position: relative; left: -50%;">
			{% for msg in messages %}
				<div class="message-{% if msg.tags %}{{ msg.tags }}{% else %}info{% endif %}" >{{ msg }}</div>
			{% endfor %}
		</div>
	</div>
	{% endif %}
    
    {% block body %}
    {% endblock %}
     
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
  </div>
  
  
  <div id="footer">
    <div class="container">
      <p class="muted credit">
        <p class="muted credit">&reg;Pagina desarrollada en la 
        <a href="http://www.usb.ve/"> Universidad Sim&oacute;n Bol&iacute;var</a> 
        para el 
        <a href="http://www.centromedicodecaracas.com.ve/">Centro M&eacute;dico de Caracas </a>.
      </p>
    </div>
  </div>
  
</body>
</html>

templates/censo.html
{% extends "base.html" %}

{% block styles %}
<!-- DataTables CSS -->
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}libs/jquery/themes/dataTables/jquery.dataTables.css">
{% endblock %}

{% block scripts %}
<!-- DataTables -->
<script type="text/javascript" charset="utf8" src="{{ STATIC_URL }}libs/jquery/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="{{ STATIC_URL }}libs/jquery/js/jquery.dataTables.columnFilter.js"></script>

<script> 
   $(document).ready(function() {
    $('#tabla_censo').dataTable( {
        "paging":   false,
        "scrollY":  300,
        "info":     false,
        "autoWidth": false
       
    } ).columnFilter({
            aoColumns: [ 
                { type: "text" },
                { type: "text" },
                { type: "text" },
                { type: "text" },
                { type: "text" },
                { type: "text" },
                { type: "select" },
                null
            ]

        });
  } );
    
</script>

<script>
    $(function() {
        var elements = document.getElementsByClassName("coloreable");
        var coloreable;
        for (var i = 0; i < elements.length; i++) {
            coloreable = elements[i];
            num = coloreable.innerHTML;
            if ( 0<= num && num <= 2) {
                coloreable.className += " verde";
            } else if (num <= 4) {
                coloreable.className += " amarillo";
            } else if (num >= 5) {
                coloreable.className += " rojo";
            }
        }
    });
    
    $(function() {
        var elements = document.getElementsByClassName("hidden-coloreable");
        var coloreable;
        for (var i = 0; i < elements.length; i++) {
            coloreable = elements[i];
            bool = coloreable.innerHTML;
            if (bool == 1) {
                var alt = $(elements[i]).attr("alt");
                $('.' + alt).addClass("amarillo_claro");
            }
        }
    });
    
    function dar_alta( item ) {
        if (confirm("Realmente desea dar de alta a este paciente?")) {
            $( item ).find('img').attr("src", "/static/img/alta_dis.png");
        //     $( item ).innerHTML = "En proceso";
            var $objeto = $( item ).parent();
            var alt = $objeto.attr("alt");
            $('.' + alt).removeClass("amarillo_claro");
            $('.' + alt).addClass("azul_claro");
        }
    }  
  </script>
{% endblock %}

{% block body %}
<div class="row">
    <div class="cuadroGrande centrar">
      <h4>
        <center><u>Censo</u></center>
      </h4>  
      <h5><center> {{ hoy }} </center></h5>
      {% if ingresos %}
        <table id="tabla_censo">
            <thead>
                <tr>
                    <th>N&uacute;mero de Habitaci&oacute;n</th>
                    <th>Paciente</th>
                    <th>M&eacute;dico</th>
                    <th>Fecha estimada de salida</th>
                    <th>Nro. D&iacute;as en la habitaci&oacute;n</th>
                    <th>Nro. D&iacute;as en la instituci&oacute;n</th>
                    <th>Procedencia</th>
                    <th>Dar alta</th>
                </tr>
            </thead>
                       
            <tbody>
                {% for ingreso in ingresos %}
                <div alt="{{ ingreso.id }}" class="hidden-coloreable" style="display: none;">
                    {{ ingreso.es_hoy }}
                </div>
                <tr>
                  <td class="{{ ingreso.id }}">
                      {{ ingreso.habitacion.numero }}
                  </td>
                  <td class="{{ ingreso.id }}">
                      {{ ingreso.solicitud.paciente }}
                  </td>
                  <td class="{{ ingreso.id }}">
                      Dr. {{ ingreso.solicitud.medico }}
                  </td>
                  <td class="{{ ingreso.id }}">
                      {{ ingreso.solicitud.salida }}
                  </td>
                  <td class="coloreable" style="font-size: 25px; color: white">
                      {{ ingreso.num_dias }}
                  </td>
                  <td class="coloreable" style="font-size: 25px; color: white">
                      {{ ingreso.solicitud.paciente.ingreso }}
                  </td>
                  <td class="{{ ingreso.id }}">
                       {{ ingreso.procedencia }}
                  </td>
                  <td alt="{{ ingreso.id }}" class="{{ ingreso.id }}">
                      <a onclick="dar_alta(this);" href="#"><img class="marginleft5 width40" src="/static/img/alta_en.png" /></a>
                  </td>
                </tr>
                {% endfor %}
            </tbody>
      </table>
      {% else %}
      <h4>No hay pacientes en este momento.</h4>
      {% endif %}
    </div>
  </div>

{% endblock %}
        
       

templates/crear_usuario.html
{% extends "base.html" %}

{% block body %}
  {% if mensaje %}
    {{ mensaje }}
  {% endif %}
  <div class="row">
    <div class="cuadroGrande span12 centrar">
      <h4>
        Crear Nuevo Usuario
      </h4>
      <form class= "tablaAgregar" method="post" action="/usuario/crear">
        {% csrf_token %}
        <table>
          <tr>
            <td>C&eacute;dula</td>
            <td>{{form.cedula}}</td>
            <td><span class="msj-error"> {{form.cedula.errors}} </span></td>
          </tr>
          <tr>
          <td>Nombres</td>
            <td>{{form.nombres}}</td>
            <td>
              <span class="msj-error"> 
                {{form.nombres.errors}}
              </span>
            </td>
          </tr>
          
          <tr>
            <td>Apellidos</td>
            <td>{{form.apellidos}}</td>
            <td>
              <span class="msj-error"> 
                {{form.apellidos.errors}}
              </span>
            </td>
          </tr>
          
          <tr>
            <td>Tipo</td>
            <td>{{form.tipo}}</td>
            <td>
              <span class="msj-error"> 
                {{form.tipo.errors}} 
              </span>
            </td>
          </tr>
          
          <tr>
            <td>Email</td>
            <td>{{form.email}}</td>
            <td>
              <span class="msj-error"> 
                {{form.email.errors}} 
              </span>
            </td>
          </tr>
          
          <tr>
            <td>Confirmaci&oacute;n de Email</td>
            <td>{{form.email0}}</td>
            <td>
              <span class="msj-error"> 
                {{form.email0.errors}} 
              </span>
            </td>
          </tr>

          <tr>
            <td>Clave</td>
            <td>{{form.clave}}</td>
            <td>
              <span class="msj-error"> 
                {{form.clave.errors}} 
              </span>
            </td>
          </tr>
          
          <tr>
            <td>Confirmar Clave</td>
            <td>{{form.clave0}}</td>
            <td>
              <span class="msj-error"> 
                {{form.clave0.errors}} 
              </span>
            </td>
          </tr>
          
          <tr>
            <td></td>
            <td>{{form.administrador}} Agregar usuario como Administrador
            </td>
            <td>
              <span class="msj-error">
                {{form.administrador.errors}} 
              </span>
            </td>
          </tr>
          
          <tr>
            <td></td>
            <td>
              <input class="btn btn-primary" 
                     type="submit" 
                     value="Crear Usuario" />
            </td>
          </tr>
        </table>
      </form>
    </div>
  </div>
{% endblock %}

templates/estadistica_matriz.html
{% extends "base.html" %}

{% block styles %}
{% endblock %}

{% block body %}
  
   <table  style="text-align:left">
	<tr>
		<td width="10%">
			<h4 style="color:grey">
				Vista matriz
			</h4>
		</td>
		
		<td width="4%">
			<h4>|</h4>
		</td>
		
		<td width="50%" >
			<h4>
			<a href="/estadisticas/termometro/">
				Vista term&oacute;metro
			</a>
			</h4>
		</td>
	</tr>
  </table>
  
	<div class="row">
		<div class="titulo">
			Matriz
		</div>
		<br>
		<h4><center> Al d&iacute;a {{ hoy }} </center></h4>
		<br>
	</div>
	<br>
	<div class="row">
		<div class="cuadroGrande centrar span10 offset1">
			<table class="table table-bordered">
			{% for hab in habs %}
				{% cycle '<tr>' '' '' '' '' '' '' '' '' '' '' '' '' '' '' %}
					<td class="{{ hab.estado }}">{{ hab.numero }}</td>
				{% cycle '' '' '' '' '' '' '' '' '' '' '' '' '' '' '</tr>' %}
			{% endfor %}
			</table>
			<table>
				<tr>
				<h5>Leyenda:</h5>
				<td width="5%" style="background:#00000;border: 1px solid black;"> </td>
				<td> Disponible. </td>
				<td width="5%"> </td>
				<td width="5%" style="background:#99FFFF;border: 1px solid black;"> </td>
				<td> En proceso de alta. </td>
				<td width="5%"> </td>
				<td width="5%" style="background:#00CC33;border: 1px solid black;">  </td>
				<td> En proceso de limpieza. </td>
				<td width="5%"> </td>
				<td width="5%" style="background:#FFFF99;border: 1px solid black;">  </td>
				<td> Ocupada. </td>
				<td width="5%"> </td>
				<td  width="5%" style="background:#FF0000;border: 1px solid black;">  </td>
				<td> En mantenimiento. </td>				
				</tr>
			</table>
		</div>
	</div>

{% endblock %}